server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: messagesender
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://psql:5432/message}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

